version: 0.2
phases:
  install:
    nodejs: 14
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm build
artifacts:
  baseDirectory: /dist/
  files:
    - src/**/*
    - package.json
